### ISSUE TITLE
Error while processing with hbGIS (building whenwhatwhere, st_geos_binop)

### ISSUE THREAD

**Issue by josefheidler** [habitus-eu/hbGIS#26]
I have this error while trying to process the data with Habitus. Can you elaborate on what is wrong, please? Thanks!

### Error message hbGIS processing
```
<<< building whenwhatwhere...
Error in stopifnot(!inherits(x, "sf"), !missing(sf_column_name), !missing(agr)) : 
  ℹ In argument: `at_home = palms_in_polygon(...)`.
Caused by error in `st_geos_binop()`:
! st_crs(x) == st_crs(y) is not TRUE
```

### Files + configs
[study.zip](https://github.com/user-attachments/files/16142865/study.zip)

**Comment by vincentvanhees** [comment]
The zip file does not include the hbGPS output. Could you share that too?

**Comment by josefheidler** [comment]
You should be able to run the whole pipeline by yourself to get the hbGPS output, and I expect you to have the same error as me, that is why I shared everything, but there you go. The whole output from the pipeline.

[output.zip](https://github.com/user-attachments/files/16231736/output.zip)

Thanks!

**Comment by vincentvanhees** [comment]
The error is caused because the GIS files do not have a coordinate reference system specified.
I just experimented with adding a line of code to set it to WGS 84 when it is missing, this works well and allows hbGIS to process the files.

Proposal:
1. Update hbGIS to produce informative error when CRS is missing in GIS files.
2. Update documentation that CRS always needs to be specified in the GIS files.

Or do you think we should add a hbGIS option to specify a back-up CRS in case it is missing from the GIS files?

**Comment by josefheidler** [comment]
Hey Vincent,

Thank you. You were right; I exported the GIS files again, and now it works; however, I encountered different problems.

Respond to your questions:

1. Yes, that would be nice.
2. Yes.

Don't do the back-up CRS. That could lead to processing mistakes.
